const text = [
    'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio, aliquid.',
    'Veritatis perspiciatis tempora voluptates, omnis fugiat, optio quos eveniet ratione ex excepturi perferendis dolorum explicabo neque?',
    'Mollitia blanditiis minus dolorum ea molestiae nostrum corporis fugit magnam libero totam ipsam ducimus, nobis incidunt delectus sapiente ex odit dicta perspiciatis excepturi soluta similique iusto rem quis quam! Animi dignissimos soluta perspiciatis? ',
    'Nesciunt autem asperiores laboriosam rerum accusamus ducimus eligendi at magni cumque dolores! Ratione ipsa amet natus pariatur autem at fugiat asperiores nesciunt illo ab, nemo architecto sequi, nobis ex! Perspiciatis provident odio eligendi molestiae.',
    'Modi molestiae eveniet error esse nam. Deleniti dolores ipsa debitis excepturi voluptatum? At error perspiciatis officia iusto quo ut deleniti dignissimos nostrum necessitatibus, repellendus voluptas ab maxime natus consequatur placeat aliquid debitis, ratione magni corporis quaerat.',
    'Molestiae aliquid repellendus nemo iusto velit consequuntur fuga officiis animi labore cumque saepe ut quis impedit sapiente, hic fugit officia, beatae veniam sed possimus adipisci quia cum. Repudiandae possimus consequuntur, reiciendis vitae magni, quod doloribus dolor vel ipsam, provident iure?',
    'Aliquid ullam excepturi sunt. Officiis, repellat voluptate! Inventore dolorem voluptatem numquam facere ipsa modi explicabo deleniti, vel, consectetur facilis quos vitae porro pariatur architecto eveniet minus animi illum. Deleniti sequi natus quisquam dolorum vel iste doloremque eius provident ipsa exercitationem. ',
    'Commodi, nisi? Tempore labore repellendus excepturi debitis iusto animi necessitatibus maiores omnis adipisci amet consectetur dolorum quaerat ea praesentium delectus est, nam perferendis assumenda dolore ex repellat eaque ipsam magnam. Nisi et porro quam facilis atque ipsum vero! Eaque reprehenderit expedita, beatae architecto eum aut, commodi quos placeat dicta fugit culpa dignissimos accusamus qui et temporibus libero. Minima commodi soluta fugit, est modi quod a alias unde atque quae sunt, ipsam enim natus sint quis non harum perferendis aliquid eum iste cum sapiente molestias sit recusandae.',
    'Deserunt quibusdam impedit adipisci perferendis repudiandae aliquid? Saepe, cum odio sed voluptates sapiente voluptatibus animi quam totam iure ipsum neque excepturi doloremque rem quae adipisci nesciunt quos assumenda. Saepe ut enim facilis provident ipsa deserunt obcaecati dolor accusantium corrupti vel quasi perspiciatis tempore vitae, nesciunt incidunt magnam repellat voluptates dolorem mollitia.',
    'Impedit voluptatem sunt, assumenda placeat dolorum harum sequi repudiandae! Excepturi, rem corporis repudiandae ipsam accusantium similique commodi ipsum, vel, harum hic officiis sequi ullam ducimus consequatur architecto qui explicabo voluptatem tempora modi error magnam est nam eos eveniet? ',
];

export default text;