export const allProjects = [
    {
        id: 1,
        name: 'Birthday Reminder',
        demoLink: 'https://birthday-reminder-47d2c8.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/bday-reminder',
        image: './images/bday-reminder.jpg',
        category: 'basic',

    },
    {
        id: 2,
        name: 'Lorem Ipsum Generator',
        demoLink: 'https://lorem-generator-00f98f.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/lorem-generator',
        image: './images/lorem-generator.jpg',
        category: 'basic',

    },
    {
        id: 3,
        name: 'Color Generator',
        demoLink: 'https://color-generator-850bfe.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/color-generator',
        image: './images/color-generator.jpg',
        category: 'basic',

    },
    {
        id: 4,
        name: 'Grocery List',
        demoLink: 'https://grocery-list-0aa1b1.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/grocery-list',
        image: './images/shopping-list.jpg',
        category: 'basic',
    },
    {
        id: 5,
        name: 'Navbar',
        demoLink: 'https://navbar-917f75.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/navbar',
        image: './images/navbar.jpg',
        category: 'basic',
    },
    {
        id: 6,
        name: 'Sidebar',
        demoLink: 'https://sidebar-aeea7d.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/sidebar',
        image: './images/sidebar.jpg',
        category: 'basic',
    },
    {
        id: 7,
        name: 'Stripe Hero Section',
        demoLink: 'https://stripe-2-d115cc.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/stripe-clone',
        image: './images/stripe.jpg',
        category: 'basic',
    },
    {
        id: 8,
        name: 'Reviews',
        demoLink: 'https://reviews-1ea56f.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/reviews',
        image: './images/reviews.jpg',
        category: 'basic',
    },
    {
        id: 9,
        name: 'Q&A',
        demoLink: 'https://qa-a93225.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/accordion',
        image: './images/qa.jpg',
        category: 'basic',
    },
    {
        id: 10,
        name: 'Food Menu',
        demoLink: 'https://food-menu-e78227.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/food-menu',
        image: './images/food-menu.jpg',
        category: 'basic',
    },
    {
        id: 11,
        name: 'Slider',
        demoLink: 'https://slider-0d1824.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/slider',
        image: './images/slider.jpg',
        category: 'basic',
    },
    {
        id: 12,
        name: 'Cart',
        demoLink: 'https://cart-6a0c40.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/cart',
        image: './images/cart.jpg',
        category: 'advanced',
    },
    {
        id: 13,
        name: 'Cocktails',
        demoLink: 'https://cocktails-ca2c4d.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/cocktails',
        image: './images/cocktails.jpg',
        category: 'advanced',
    },
    {
        id: 14,
        name: 'Markdown',
        demoLink: 'https://markdown-f6a1ca.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/markdown',
        image: './images/markdown.jpg',
        category: 'advanced',
    },
    {
        id: 15,
        name: 'Random User',
        demoLink: 'https://random-user-60ca3c.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/random-user',
        image: './images/random-user.jpg',
        category: 'advanced',
    },
    {
        id: 16,
        name: 'Pagination',
        demoLink: 'https://pagination-5a3c2b.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/pagination',
        image: './images/pagination.jpg',
        category: 'advanced',
    },
    {
        id: 17,
        name: 'Dark Mode',
        demoLink: 'https://dark-mode-eae40e.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/dark-mode',
        image: './images/dark-mode.jpg',
        category: 'basic',
    },
    {
        id: 18,
        name: 'Stock Photos',
        demoLink: 'https://stock-photos-68d44d.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/stock-photos',
        image: './images/stock-photos.jpg',
        category: 'advanced',
    },
    {
        id: 18,
        name: 'Hacker News',
        demoLink: 'https://hacker-news-6e7649.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/hacker-news',
        image: './images/hacker-news.jpg',
        category: 'advanced',
    },
    {
        id: 19,
        name: 'Quiz',
        demoLink: 'https://quiz-14d501.netlify.app/',
        repoLink: 'https://github.com/VentsiGeorgiev/react-tutorial-and-projects/tree/main/projects/quiz',
        image: './images/quiz.jpg',
        category: 'advanced',
    },

];